spring:
  application:
    name: jwt

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    # show-sql: true

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/tech_shop_auth_api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gearvn?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    # url: ${MYSQL_URL}
    # username: ${MYSQL_USER}
    # password: ${MYSQL_PASSWORD}



server:
  port: 8081
